# Generated by Django 2.0.5 on 2018-05-30 16:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Boiler',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_post', models.IntegerField(choices=[(1, 1), (3, 3)])),
                ('date_time', models.DateTimeField()),
                ('second_on', models.IntegerField()),
                ('usage_ccf', models.FloatField()),
                ('temperature', models.FloatField()),
                ('hhd_60', models.FloatField()),
                ('hdd_62_5', models.FloatField()),
                ('hdd_65', models.FloatField()),
                ('hdd_67_5', models.FloatField()),
                ('hhd_70', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bdbid', models.IntegerField(unique=True)),
                ('building_name', models.CharField(max_length=150)),
                ('retrofit_type', models.CharField(choices=[('Pump', 'Pump'), ('Boiler', 'Boiler')], max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Pump',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pre_post', models.IntegerField(choices=[(1, 1), (3, 3)])),
                ('date_time', models.DateTimeField()),
                ('motor_on', models.IntegerField(choices=[(1, 1), (0, 0)])),
                ('motor_off', models.IntegerField(choices=[(1, 1), (0, 0)])),
                ('pump', models.IntegerField(choices=[(1, 1), (0, 0)])),
                ('bdbid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Building', to_field='bdbid')),
            ],
        ),
        migrations.AddField(
            model_name='boiler',
            name='bdbid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Building', to_field='bdbid'),
        ),
    ]
