# Generated by Django 2.0.5 on 2018-05-30 16:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boiler',
            old_name='hhd_60',
            new_name='hdd_60',
        ),
        migrations.RenameField(
            model_name='boiler',
            old_name='hhd_70',
            new_name='hdd_70',
        ),
    ]
