# Generated by Django 2.0.5 on 2018-05-30 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_auto_20180530_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pump',
            name='pump',
            field=models.IntegerField(choices=[(1, 1), (2, 2)]),
        ),
    ]
