# Generated by Django 2.0.5 on 2018-05-31 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0005_auto_20180531_0436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='boiler',
            name='bdbid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Building'),
        ),
        migrations.AlterField(
            model_name='pump',
            name='bdbid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dashboard.Building'),
        ),
    ]
