# Generated by Django 2.0.5 on 2018-05-31 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0006_auto_20180531_0501'),
    ]

    operations = [
        migrations.AddField(
            model_name='boiler',
            name='boiler',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
